// Auto-generated by build-riskorg.js — do not edit directly


// --- GameResultAdjuster.js ---
// GameResultAdjuster

// --- RiskFlowManager.js ---
// RiskFlowManager

// --- riskorg.js ---

function init() {
  remoteLog('沙箱代码执行成功');
}
